#pragma config(Sensor, in1,    arm_potentiometer, sensorPotentiometer)
#pragma config(Sensor, in2,    light_sensor,   sensorReflection)
#pragma config(Sensor, in6,    line_sensor_right, sensorLineFollower)
#pragma config(Sensor, in7,    line_sensor_center, sensorLineFollower)
#pragma config(Sensor, in8,    line_sensor_left, sensorLineFollower)
#pragma config(Sensor, dgtl1,  ultrasonicSonar, sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  arm_limit,      sensorTouch)
#pragma config(Sensor, dgtl4,  emergency_button, sensorTouch)
#pragma config(Sensor, dgtl8,  left_encoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl10, right_encoder,  sensorQuadEncoder)
#pragma config(Motor,  port2,           right_motor,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           left_motor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           arm_motor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           claw_motor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../headers/constants.c";
#include "../functions/motor_functions.c";
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Verkefni 4 -                                         		*|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*  While the light sensor detects light this program is active and uses the sonar sensor to avoid    *|
|*  crashing into objects infront of the robot. 				                                              *|
\*----------------------------------------------------------------------------------------------------*/

task emergency_stop(){
	while (SensorValue[emergency_button] == 0 || vexRT[Btn8U] == 1){
	}
	StopAllTasks();
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

task main(){
	StartTask(emergency_stop);
	while (true){
		while(SensorValue(light_sensor) < 300){
			if(SensorValue(ultrasonicSonar) > 35){
				reset_encoder();
				drive(100, true);
				stop_motors();
			}
			else{
				stop_motors();
				wait1Msec(500);
				reset_encoder();
				turn(90, true);
				stop_motors();
				wait1Msec(500);
			}
		}
	}
}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
