#pragma config(Sensor, in1,    arm_potentiometer, sensorPotentiometer)
#pragma config(Sensor, in2,    light_sensor,   sensorReflection)
#pragma config(Sensor, in6,    line_sensor_right, sensorLineFollower)
#pragma config(Sensor, in7,    line_sensor_center, sensorLineFollower)
#pragma config(Sensor, in8,    line_sensor_left, sensorLineFollower)
#pragma config(Sensor, dgtl1,  ultrasonicSonar, sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  arm_limit,      sensorTouch)
#pragma config(Sensor, dgtl4,  emergency_button, sensorTouch)
#pragma config(Sensor, dgtl8,  left_encoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl10, right_encoder,  sensorQuadEncoder)
#pragma config(Motor,  port2,           right_motor,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           left_motor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           arm_motor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           claw_motor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*

#include "../headers/constants.c";
#include "../functions/motor_functions.c";
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Verkefni 6 -                                         		*|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*  This program uses the line sensors to follow a line.                                              *|
\*----------------------------------------------------------------------------------------------------*/
bool has_silo = false;

//---------------------Global Tasks-------------------------

task emergency_stop(){
	while (SensorValue[emergency_button] == 0 || vexRT[Btn8U] == 1){
	}
	StopAllTasks();
}

//--------------------------Verkefni 2------------------------

task verkefni2a(){
	for(int i=1;i<5;i++){
	stop_motors();
	wait1Msec(500);
	drive_time(i,true);
	stop_motors();
	wait1Msec(500);
	drive_time(i,false);
	}
}

task verkefni2b(){
	for(int i=1;i<5;i++){
	reset_encoder();
	stop_motors();
	wait1Msec(500);
	drive(BASEDIST*i,true);
	reset_encoder();
	stop_motors();
	wait1Msec(500);
	drive(BASEDIST*i,false);
	}
}

task verkefni2c(){
	reset_encoder();
	drive(BASEDIST,true);
	stop_motors();
	reset_encoder();
	wait1Msec(500);
	turn(90, true);
	stop_motors();
	reset_encoder();
	wait1Msec(500);
	for (int i=1;i<3;i++){
	drive(BASEDIST,true);
	stop_motors();
	reset_encoder();
	wait1Msec(500);
	turn(90, false);
	stop_motors();
	reset_encoder();
	wait1Msec(500);
	}
	drive(BASEDIST,true);
}
//-----------------------------verkefni 3-----------------

task controller(){
	int joy_l;
	int joy_r;
	while (true){
		if (vexRT[Btn8U] == 1){
			break;
		}
		joy_l = vexRT[Ch4];
		joy_r = vexRT[Ch2];
		if((abs(joy_r) > controller_threshold))
		{
			motor[left_motor]  = (joy_r)/2;
			motor[right_motor] = (joy_r)/2;
		}
		if((abs(joy_l) > controller_threshold))
		{
			motor[left_motor]  = (joy_l)/2;
			motor[right_motor] = -(joy_l)/2;
		}

		if (vexRT[Btn6D] == 1){
			motor[arm_motor]=low_power;
		}
		if (vexRT[Btn6U] == 1){
			motor[arm_motor]=-power;
		}
		if (vexRT[Btn5D] == 1){
			motor[claw_motor]=low_power;
		}
		if (vexRT[Btn5U] == 1){
			motor[claw_motor]=-power;
		}
		wait1Msec(100);
		stop_motors();
	}
}

//-------------------Vekefni 4-----------------

task verkefni4(){
	while (true){
		while(SensorValue(light_sensor) < 300){
			if(SensorValue(ultrasonicSonar) > 35){
				reset_encoder();
				drive(100, true);
				stop_motors();
			}
			else{
				stop_motors();
				wait1Msec(500);
				reset_encoder();
				turn(90, true);
				stop_motors();
				wait1Msec(500);
			}
		}
	}
}

//---------------------------Verkefni 5-------------------

task line_follower(){
	while(true)
  {
    if(SensorValue(line_sensor_right) > line_threshold)
    {
      motor[left_motor]  = power;
      motor[right_motor] = no_power;
    }
    if(SensorValue(line_sensor_center) > line_threshold)
    {
      motor[left_motor]  = power;
      motor[right_motor] = power;
    }
    if(SensorValue(line_sensor_left) > line_threshold)
    {
      motor[left_motor]  = no_power;
      motor[right_motor] = power;
    }
    if(SensorValue(line_sensor_center) < 1900)
  	{
    	motor[left_motor]  = power;
      motor[right_motor] = -power;
    }
  }
  StopTask(line_follower);
}

//-----------------------Verkefni 6-------------------------------

task take_silo(){
	stop_wait1sec();
	motor[claw_motor]=-50;
	wait1Msec(1000);
	stop_wait1sec();
	while(SensorValue(ultrasonicSonar) > 20){
		motor[left_motor]  = low_power;
  	motor[right_motor] = low_power;
	}
  stop_wait1sec();
	motor[claw_motor]=40;
	wait1Msec(1000);
	stop_wait1sec();

	while(SensorValue(arm_potentiometer) < potent_arm_limit){
		motor[arm_motor]=-50;
	}
	stop_wait1sec();
	reset_encoder();
	turn(180, false);
	stop_wait1sec();
}

task drop_silo(){
	stop_wait1sec();
	while(SensorValue(ultrasonicSonar) > 20){
		motor[left_motor]  = low_power;
  	motor[right_motor] = low_power;
	}
  stop_wait1sec();
  motor[claw_motor]=-50;
	wait1Msec(1000);
	stop_wait1sec();
}

task verkefni6(){
	while (true){
		StartTask(line_follower);
		while(has_silo == false){
			if(SensorValue(ultrasonicSonar) < 30){
				StopTask(line_follower);
				StartTask(take_silo);
				while(SensorValue(ultrasonicSonar) < 30){
				}
				has_silo = true;
			}
		}
		wait1Msec(5000);
		stop_wait1sec();
		StartTask(line_follower);
		while(has_silo){
			if(SensorValue(ultrasonicSonar) < 30 & has_silo){
				StopTask(line_follower);
				StartTask(drop_silo);
				while(SensorValue(ultrasonicSonar) < 30){
				}
			}
	  }
	}
}
//----------------------------Task------------------------------
task button_task(){
	while (true){
		if (vexRT[Btn8R] == 1){
			StopTask(verkefni2a);
			StopTask(verkefni2b);
			StopTask(verkefni2c);
			StopTask(controller);
			StopTask(line_follower);
			StopTask(verkefni6);
			stop_motors();
		}
	}
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

task main(){
	StartTask(emergency_stop);
	StartTask(button_task);
	while (true){
		if (vexRT[Btn8D] == 1){
			StartTask(controller);
		}
		if (vexRT[Btn7U] == 1){
			StartTask(verkefni2a);
		}
		if (vexRT[Btn7D] == 1){
			StartTask(verkefni2b);
		}
		if (vexRT[Btn6D] == 1){
			StartTask(verkefni2c);
		}
		if (vexRT[Btn6U] == 1){
			StartTask(verkefni4);
		}
		if (vexRT[Btn5D] == 1){
			StartTask(line_follower);
			}
		if (vexRT[Btn5U] == 1){
			StartTask(verkefni6);
		}
	}
}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
