#pragma config(Sensor, in1,    arm_potentiometer, sensorPotentiometer)
#pragma config(Sensor, in2,    light_sensor,   sensorReflection)
#pragma config(Sensor, in6,    line_sensor_right, sensorLineFollower)
#pragma config(Sensor, in7,    line_sensor_center, sensorLineFollower)
#pragma config(Sensor, in8,    line_sensor_left, sensorLineFollower)
#pragma config(Sensor, dgtl1,  ultrasonicSonar, sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  arm_limit,      sensorTouch)
#pragma config(Sensor, dgtl4,  emergency_button, sensorTouch)
#pragma config(Sensor, dgtl8,  left_encoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl10, right_encoder,  sensorQuadEncoder)
#pragma config(Motor,  port2,           right_motor,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           left_motor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           arm_motor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           claw_motor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Verkefni 2 A -                                           *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward 0.5m and then back 0.5m, then 1m and so on      *|
|*  until he has reached 2.5m. Use time to measure the distance he traveles.                          *|
\*----------------------------------------------------------------------------------------------------*/
int power = 127;

const int BASETIME = 1000;

void stop_motors(){
	motor[right_motor]=0;
	motor[left_motor]=0;
	motor[claw_motor]=0;
	motor[arm_motor]=0;
}

void drive(int counter,bool bf){
	if(bf){
	motor[right_motor] = power;
	motor[left_motor]  = power;
	wait1Msec(BASETIME*counter);
}
	else{
		motor[right_motor] = -power;
		motor[left_motor]  = -power;
		wait1Msec(BASETIME*counter);
		}
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main(){

	for(int i=1;i<5;i++){
	stop_motors();
	wait1Msec(500);
	drive(i,true);
	stop_motors();
	wait1Msec(500);
	drive(i,false);
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
