#pragma config(Sensor, in1,    arm_potentiometer, sensorPotentiometer)
#pragma config(Sensor, in2,    light_sensor,   sensorReflection)
#pragma config(Sensor, in6,    line_sensor_right, sensorLineFollower)
#pragma config(Sensor, in7,    line_sensor_center, sensorLineFollower)
#pragma config(Sensor, in8,    line_sensor_left, sensorLineFollower)
#pragma config(Sensor, dgtl1,  ultrasonicSonar, sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  arm_limit,      sensorTouch)
#pragma config(Sensor, dgtl4,  emergency_button, sensorTouch)
#pragma config(Sensor, dgtl8,  left_encoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl10, right_encoder,  sensorQuadEncoder)
#pragma config(Motor,  port2,           right_motor,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           left_motor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           arm_motor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           claw_motor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|                *|
\*-----------------------------------------------------------------------------------------------4246-*/
int power = 127;
//   d = 4" or 2.54*4
//   d = 10.16
//   Ummal_hj = d * Pi
//   Ummal_hj = 10.16 * 3.14 = 31.9
//   Base_dist = 50cm/Umml_hj*360
//   50/31.9*360 = 564.26

//Timi til a fara 0.5 metra
const int BASEDIST = 564;

//bool = True or False
void drive(int dist,bool bf){
	// ef bf = True, dir = 1, else, dir = -1
	int dir = (bf)? (1): (-1);
	if(bf){
		while(dist < SensorValue[right_encoder]){
		if(SensorValue[right_encoder] == SensorValue[left_encoder]) // If right_encoder has counted the same amount as left_encoder:
		{
			// Move Forward
			motor[right_motor] = 80*dir;		    // Right Motor is run at power level 80
			motor[left_motor]  = 80*dir;		    // Left Motor is run at power level 80
		}
		else if(SensorValue[right_encoder] > SensorValue[left_encoder])	// If left_encoder has counted more encoder counts
		{
			// Turn slightly right
			motor[right_motor] = 60*dir;		    // Right Motor is run at power level 60
			motor[left_motor]  = 80*dir;		    // Left Motor is run at power level 80
		}
		else	// Only runs if left_encoder has counted more encoder counts
		{
			// Turn slightly left
			motor[right_motor] = 80*dir;		    // Right Motor is run at power level 80
			motor[left_motor]  = 60*dir;		    // Left Motor is run at power level 60
		}
	}
}
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main(){
	for(int i=1;i<5;i++){
	drive(BASEDIST*i,true);
	drive(BASEDIST*i,false);
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
