
#pragma config(Sensor, in1,    arm_potentiometer, sensorPotentiometer)
#pragma config(Sensor, in2,    light_sensor,   sensorReflection)
#pragma config(Sensor, in6,    line_sensor_right, sensorLineFollower)
#pragma config(Sensor, in7,    line_sensor_center, sensorLineFollower)
#pragma config(Sensor, in8,    line_sensor_left, sensorLineFollower)
#pragma config(Sensor, dgtl1,  ultrasonicSonar, sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  arm_limit,      sensorTouch)
#pragma config(Sensor, dgtl4,  emergency_button, sensorTouch)
#pragma config(Sensor, dgtl8,  left_encoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl10, right_encoder,  sensorQuadEncoder)
#pragma config(Motor,  port2,           right_motor,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           left_motor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           arm_motor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           claw_motor,    tmotorServoContinuousRotation, openLoop)

#include "../headers/constants.c";
#include "../functions/motor_functions.c";
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
|*		//   d = 4" or 2.54*45                                                                          *|
|*		//   d = 10.16                                                                                  *|
|*		//   Ummal_hj = d * Pi                                                                          *|
|*		//   Ummal_hj = 10.16 * 3.14 = 31.9                                                             *|
|*		//   Base_dist = 50cm/Umml_hj*360                                                               *|
|*		//   50/31.9*360 = 564.26*|                                                                     *|
\*-----------------------------------------------------------------------------------------------4246-*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main(){

	reset_encoder();
	drive(BASEDIST,true);
	reset_encoder();
	turn(90, true);
	reset_encoder();
	drive(BASEDIST,true);
	reset_encoder();
	turn(90, false);
	reset_encoder();
	drive(BASEDIST,true);
	reset_encoder();
	turn(90, false);
	reset_encoder();
	drive(BASEDIST,true);

}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
