#pragma config(Sensor, in1,    arm_potentiometer, sensorPotentiometer)
#pragma config(Sensor, in2,    light_sensor,   sensorReflection)
#pragma config(Sensor, in6,    line_sensor_right, sensorLineFollower)
#pragma config(Sensor, in7,    line_sensor_center, sensorLineFollower)
#pragma config(Sensor, in8,    line_sensor_left, sensorLineFollower)
#pragma config(Sensor, dgtl1,  ultrasonicSonar, sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  arm_limit,      sensorTouch)
#pragma config(Sensor, dgtl4,  emergency_button, sensorTouch)
#pragma config(Sensor, dgtl8,  left_encoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl10, right_encoder,  sensorQuadEncoder)
#pragma config(Motor,  port2,           right_motor,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           left_motor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           arm_motor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           claw_motor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../headers/constants.c";
#include "../functions/motor_functions.c";
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Verkefni 6 -                                         		*|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*  This program uses the line sensors to follow a line.                                              *|
\*----------------------------------------------------------------------------------------------------*/
bool has_silo;

task emergency_stop(){
	while (SensorValue[emergency_button] == 0 || vexRT[Btn8U] == 1){
	}
	StopAllTasks();
}

task line_follower(){
	if(SensorValue(line_sensor_right) > line_threshold)
  {
    motor[left_motor]  = power;
    motor[right_motor] = no_power;
  }
  if(SensorValue(line_sensor_center) > line_threshold)
  {
    motor[left_motor]  = power;
    motor[right_motor] = power;
  }
  if(SensorValue(line_sensor_left) > line_threshold)
  {
    motor[left_motor]  = no_power;
    motor[right_motor] = power;
  }
}

task take_silo(){
	stop_motors();
	wait1Msec(500);
	motor[claw_motor]=-50;

	while(SensorValue(ultrasonicSonar) > 20)
		motor[left_motor]  = low_power;
  	motor[right_motor] = low_power;

  stop_motors();
	wait1Msec(500);
	motor[claw_motor]=20;


	reset_encoder();
	turn(180, true);
	stop_motors();
	wait1Msec(500);
	motor[claw_motor]=-50;
	bool has_silo = true
}


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

task main(){
	wait1Msec(10000);
	//int power = 50;
	//int low_power = 15;
	//int no_power = 0;
 // int threshold = 2500;      /* found by taking a reading on both DARK and LIGHT    */
  StartTask(emergency_stop);                          /* surfaces, adding them together, then dividing by 2. */
  while(true)
  {
  	StartTask(line_follower);
  	if(SensorValue(ultrasonicSonar) < 35)
  	{
  		if (has_silo){
			StartTask(take_silo);
			}
			else{
			}

		}
  	if(SensorValue(arm_potentiometer) < potent_arm_limit)
  	{
  		stop_arm();
  	}
  }
}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
